<?xml version="1.0" encoding="utf-8"?><Database Name="Library" Class="LibraryDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Library;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="LibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.books_on_hand" Member="books_on_hands">
    <Type Name="books_on_hand">
      <Column Name="book_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="author_firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="author_lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="short_description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="long_description" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lent_books" Member="lent_books">
    <Type Name="lent_book">
      <Column Name="book_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="author_firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="author_lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="short_description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="long_description" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
    </Type>
  </Table>
</Database>