#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Library")]
	public partial class LINQtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbook(book instance);
    partial void Updatebook(book instance);
    partial void Deletebook(book instance);
    partial void Insertregistered_reader(registered_reader instance);
    partial void Updateregistered_reader(registered_reader instance);
    partial void Deleteregistered_reader(registered_reader instance);
    partial void Insertlend_list(lend_list instance);
    partial void Updatelend_list(lend_list instance);
    partial void Deletelend_list(lend_list instance);
    #endregion
		
		public LINQtoSQLDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.LibraryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<book> books
		{
			get
			{
				return this.GetTable<book>();
			}
		}
		
		public System.Data.Linq.Table<registered_reader> registered_readers
		{
			get
			{
				return this.GetTable<registered_reader>();
			}
		}
		
		public System.Data.Linq.Table<lend_list> lend_lists
		{
			get
			{
				return this.GetTable<lend_list>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.books")]
	public partial class book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _bookID;
		
		private string _title;
		
		private string _author_first_name;
		
		private string _author_last_name;
		
		private string _description;
		
		private bool _lent;
		
		private EntitySet<lend_list> _lend_lists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbookIDChanging(decimal value);
    partial void OnbookIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onauthor_first_nameChanging(string value);
    partial void Onauthor_first_nameChanged();
    partial void Onauthor_last_nameChanging(string value);
    partial void Onauthor_last_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnlentChanging(bool value);
    partial void OnlentChanged();
    #endregion
		
		public book()
		{
			this._lend_lists = new EntitySet<lend_list>(new Action<lend_list>(this.attach_lend_lists), new Action<lend_list>(this.detach_lend_lists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal bookID
		{
			get
			{
				return this._bookID;
			}
			set
			{
				if ((this._bookID != value))
				{
					this.OnbookIDChanging(value);
					this.SendPropertyChanging();
					this._bookID = value;
					this.SendPropertyChanged("bookID");
					this.OnbookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author_first_name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string author_first_name
		{
			get
			{
				return this._author_first_name;
			}
			set
			{
				if ((this._author_first_name != value))
				{
					this.Onauthor_first_nameChanging(value);
					this.SendPropertyChanging();
					this._author_first_name = value;
					this.SendPropertyChanged("author_first_name");
					this.Onauthor_first_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author_last_name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string author_last_name
		{
			get
			{
				return this._author_last_name;
			}
			set
			{
				if ((this._author_last_name != value))
				{
					this.Onauthor_last_nameChanging(value);
					this.SendPropertyChanging();
					this._author_last_name = value;
					this.SendPropertyChanged("author_last_name");
					this.Onauthor_last_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lent", DbType="Bit NOT NULL")]
		public bool lent
		{
			get
			{
				return this._lent;
			}
			set
			{
				if ((this._lent != value))
				{
					this.OnlentChanging(value);
					this.SendPropertyChanging();
					this._lent = value;
					this.SendPropertyChanged("lent");
					this.OnlentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="book_lend_list", Storage="_lend_lists", ThisKey="bookID", OtherKey="bookID")]
		public EntitySet<lend_list> lend_lists
		{
			get
			{
				return this._lend_lists;
			}
			set
			{
				this._lend_lists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_lend_lists(lend_list entity)
		{
			this.SendPropertyChanging();
			entity.book = this;
		}
		
		private void detach_lend_lists(lend_list entity)
		{
			this.SendPropertyChanging();
			entity.book = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.registered_readers")]
	public partial class registered_reader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _readerID;
		
		private string _first_name;
		
		private string _last_name;
		
		private EntitySet<lend_list> _lend_lists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnreaderIDChanging(decimal value);
    partial void OnreaderIDChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    #endregion
		
		public registered_reader()
		{
			this._lend_lists = new EntitySet<lend_list>(new Action<lend_list>(this.attach_lend_lists), new Action<lend_list>(this.detach_lend_lists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readerID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal readerID
		{
			get
			{
				return this._readerID;
			}
			set
			{
				if ((this._readerID != value))
				{
					this.OnreaderIDChanging(value);
					this.SendPropertyChanging();
					this._readerID = value;
					this.SendPropertyChanged("readerID");
					this.OnreaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registered_reader_lend_list", Storage="_lend_lists", ThisKey="readerID", OtherKey="readerID")]
		public EntitySet<lend_list> lend_lists
		{
			get
			{
				return this._lend_lists;
			}
			set
			{
				this._lend_lists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_lend_lists(lend_list entity)
		{
			this.SendPropertyChanging();
			entity.registered_reader = this;
		}
		
		private void detach_lend_lists(lend_list entity)
		{
			this.SendPropertyChanging();
			entity.registered_reader = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lend_list")]
	public partial class lend_list : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _lend_listID;
		
		private decimal _bookID;
		
		private decimal _readerID;
		
		private EntityRef<book> _book;
		
		private EntityRef<registered_reader> _registered_reader;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlend_listIDChanging(decimal value);
    partial void Onlend_listIDChanged();
    partial void OnbookIDChanging(decimal value);
    partial void OnbookIDChanged();
    partial void OnreaderIDChanging(decimal value);
    partial void OnreaderIDChanged();
    #endregion
		
		public lend_list()
		{
			this._book = default(EntityRef<book>);
			this._registered_reader = default(EntityRef<registered_reader>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lend_listID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal lend_listID
		{
			get
			{
				return this._lend_listID;
			}
			set
			{
				if ((this._lend_listID != value))
				{
					this.Onlend_listIDChanging(value);
					this.SendPropertyChanging();
					this._lend_listID = value;
					this.SendPropertyChanged("lend_listID");
					this.Onlend_listIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookID", DbType="Decimal(18,0) NOT NULL")]
		public decimal bookID
		{
			get
			{
				return this._bookID;
			}
			set
			{
				if ((this._bookID != value))
				{
					if (this._book.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbookIDChanging(value);
					this.SendPropertyChanging();
					this._bookID = value;
					this.SendPropertyChanged("bookID");
					this.OnbookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readerID", DbType="Decimal(18,0) NOT NULL")]
		public decimal readerID
		{
			get
			{
				return this._readerID;
			}
			set
			{
				if ((this._readerID != value))
				{
					if (this._registered_reader.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnreaderIDChanging(value);
					this.SendPropertyChanging();
					this._readerID = value;
					this.SendPropertyChanged("readerID");
					this.OnreaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="book_lend_list", Storage="_book", ThisKey="bookID", OtherKey="bookID", IsForeignKey=true)]
		public book book
		{
			get
			{
				return this._book.Entity;
			}
			set
			{
				book previousValue = this._book.Entity;
				if (((previousValue != value) 
							|| (this._book.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._book.Entity = null;
						previousValue.lend_lists.Remove(this);
					}
					this._book.Entity = value;
					if ((value != null))
					{
						value.lend_lists.Add(this);
						this._bookID = value.bookID;
					}
					else
					{
						this._bookID = default(decimal);
					}
					this.SendPropertyChanged("book");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="registered_reader_lend_list", Storage="_registered_reader", ThisKey="readerID", OtherKey="readerID", IsForeignKey=true)]
		public registered_reader registered_reader
		{
			get
			{
				return this._registered_reader.Entity;
			}
			set
			{
				registered_reader previousValue = this._registered_reader.Entity;
				if (((previousValue != value) 
							|| (this._registered_reader.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._registered_reader.Entity = null;
						previousValue.lend_lists.Remove(this);
					}
					this._registered_reader.Entity = value;
					if ((value != null))
					{
						value.lend_lists.Add(this);
						this._readerID = value.readerID;
					}
					else
					{
						this._readerID = default(decimal);
					}
					this.SendPropertyChanged("registered_reader");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
